name: Cloudflare Node Selection

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-cf-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq
          export LANG=en_US.UTF-8

      - name: Debug Directory Structure
        run: |
          echo "当前目录内容："
          ls -la
          echo "cf 目录内容："
          ls -la cf || echo "cf 目录不存在"

      - name: Run cf.sh Script
        run: |
          chmod +x cf/cf.sh
          bash cf/cf.sh
        env:
          CURL_CA_BUNDLE: ""  # 忽略 SSL 验证（如果需要）

      - name: Upload Results
        if: always()  # 即使脚本失败也上传结果
        uses: actions/upload-artifact@v4
        with:
          name: cf-results
          path: |
            *.csv
          retention-days: 7
