name: Node Selector Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  selector:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl zip

      - name: Download necessary files for the script
        run: |
          curl -L -o cf.sh --retry 2 --insecure https://raw.githubusercontent.com/yonggekkk/Cloudflare_vless_trojan/main/cf/cf.sh
          chmod +x cf.sh

      - name: Run the selection script
        run: |
          bash ./cf.sh

      - name: Archive selection results
        run: |
          zip -r selection_results.zip TW-4.csv SG-4.csv TW-6.csv SG-6.csv
          
      - name: Upload results to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: selection-results
          path: selection_results.zip
