name: Node Selector Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip

      - name: Ensure cf.sh is executable
        run: |
          # 确保仓库中的 cf.sh 可执行
          chmod +x cf/cf.sh

      - name: Run the cf.sh script
        run: |
          # 直接运行仓库中已有的 cf.sh 脚本
          cd cf
          bash ./cf.sh

      - name: Archive results
        run: |
          mkdir -p archive
          zip -r archive/results_$(date +%Y%m%d%H%M%S).zip ./4.csv ./6.csv ./TW-4.csv ./SG-4.csv ./TW-6.csv ./SG-6.csv
          git add archive/results_$(date +%Y%m%d%H%M%S).zip
          git commit -m "Add results for $(date +%Y%m%d%H%M%S)"
          git push
