name: Node Selector Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip

      - name: Download and prepare necessary files
        run: |
          # Download necessary files for the script
          curl -L -o cf https://raw.githubusercontent.com/yonggekkk/Cloudflare_vless_trojan/main/cf/amd64
          chmod +x cf
          curl -s -o locations.json https://raw.githubusercontent.com/yonggekkk/Cloudflare_vless_trojan/main/cf/locations.json
          curl -s -o ips-v4.txt https://raw.githubusercontent.com/yonggekkk/Cloudflare_vless_trojan/main/cf/ips-v4.txt
          curl -s -o ips-v6.txt https://raw.githubusercontent.com/yonggekkk/Cloudflare_vless_trojan/main/cf/ips-v6.txt

      - name: Run the script
        run: |
          bash ./cf.sh

      - name: Archive results
        run: |
          mkdir -p archive
          zip -r archive/results_$(date +%Y%m%d%H%M%S).zip ./4.csv ./6.csv ./TW-4.csv ./SG-4.csv ./TW-6.csv ./SG-6.csv
          git add archive/results_$(date +%Y%m%d%H%M%S).zip
          git commit -m "Add results for $(date +%Y%m%d%H%M%S)"
          git push

