name: Node Selector Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip

      - name: Download files if not present
        run: |
          # Check if cf directory exists, skip download if it does
          if [ ! -d "cf" ]; then
            echo "Downloading cf..."
            curl -L -o cf https://raw.githubusercontent.com/yonggekkk/Cloudflare_vless_trojan/main/cf/amd64
            chmod +x cf
          else
            echo "cf already exists, skipping download."
          fi

          # Download other necessary files if they do not exist
          [ ! -e locations.json ] && curl -s -o locations.json https://raw.githubusercontent.com/yonggekkk/Cloudflare_vless_trojan/main/cf/locations.json
          [ ! -e ips-v4.txt ] && curl -s -o ips-v4.txt https://raw.githubusercontent.com/yonggekkk/Cloudflare_vless_trojan/main/cf/ips-v4.txt
          [ ! -e ips-v6.txt ] && curl -s -o ips-v6.txt https://raw.githubusercontent.com/yonggekkk/Cloudflare_vless_trojan/main/cf/ips-v6.txt

      - name: Run the script
        run: |
          # Ensure cf.sh is in the current directory
          if [ ! -f "cf.sh" ]; then
            echo "cf.sh script is missing, please verify your setup."
            exit 1
          fi
          bash ./cf.sh

      - name: Archive results
        run: |
          mkdir -p archive
          zip -r archive/results_$(date +%Y%m%d%H%M%S).zip ./4.csv ./6.csv ./TW-4.csv ./SG-4.csv ./TW-6.csv ./SG-6.csv
          git add archive/results_$(date +%Y%m%d%H%M%S).zip
          git commit -m "Add results for $(date +%Y%m%d%H%M%S)"
          git push
